version: "3.9"

services:
  jupyter:
    tty: true
    stdin_open: true
    build: .
    ports:
      - "3008:3008"
    volumes:
      - .:/src/
      - ./notebooks:/src/notebooks
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]